version: "2"
services:
  app:
    build: .
    container_name: Gov_App
    links:
      - db
    ports:
      - "5000:80"
    depends_on:
      - db
  db:
    container_name: Gov_DB
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./Core/DB/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./data:/var/lib/mysql
